In [1]:
import pandas as pd
import os
pd.options.mode.chained_assignment= None

In [2]:
files= [file for file in os.listdir('./CSV Files')]

all_matches_data=pd.DataFrame()

for file in files:
    df=pd.read_csv('./CSV Files/'+file)
    all_matches_data=pd.concat([all_matches_data,df])

In [3]:
# all_matches_data.to_csv('Combo_Match1_to_Match9.csv',index=False)

In [4]:
 df= pd.read_csv('Combo CSV Files\Combo_Match1_to_Match9.csv',index_col='Players')

In [5]:
df.head(1)

,Team,Match Played,Batsman Runs,Balls,Fours,Sixes,Strike Rate,Over,Bowler Balls,Maiden,Bowler Runs,Wickets,Economy Rate,Catches,Run Out,50s,100s,Vs,Times Out
Players,,,,,,,,,,,,,,,,,,,
Rohit Sharma,Mumbai Indians,1,19,15,1,1,126.67,0.0,0,0,0,0,0.0,0,0,0,0,RCB,Yes

In [6]:
df.Sixes.sum()

106

In [7]:
df.Fours.sum()

260

In [8]:
df.groupby('Team').Fours.sum().nlargest(8)

Team
Delhi Capitals                44
Mumbai Indians                41
Rajasthan Royals              34
Kolkata Knight Riders         32
Chennai Super Kings           28
Punjab Kings                  28
Sunrisers Hyderabad           27
Royal Challengers Banglore    26
Name: Fours, dtype: int64

In [9]:
df.groupby('Team').Sixes.sum().nlargest(8)

Team
Sunrisers Hyderabad           22
Rajasthan Royals              18
Mumbai Indians                15
Punjab Kings                  15
Chennai Super Kings           12
Kolkata Knight Riders         11
Royal Challengers Banglore     8
Delhi Capitals                 5
Name: Sixes, dtype: int64

# BATSMAN

In [10]:
df.head(1)

,Team,Match Played,Batsman Runs,Balls,Fours,Sixes,Strike Rate,Over,Bowler Balls,Maiden,Bowler Runs,Wickets,Economy Rate,Catches,Run Out,50s,100s,Vs,Times Out
Players,,,,,,,,,,,,,,,,,,,
Rohit Sharma,Mumbai Indians,1,19,15,1,1,126.67,0.0,0,0,0,0,0.0,0,0,0,0,RCB,Yes

In [11]:
batsman_played= df[['Team','Match Played','Batsman Runs','Balls','Fours','Sixes','Strike Rate','50s','100s','Vs','Times Out']]

In [12]:
Batsman= batsman_played[batsman_played['Balls'] >=1]

In [13]:
Batsman.replace(to_replace=['Yes','No'],value=[0,1],inplace=True)

In [14]:
Batsman['Times Out'] = Batsman['Times Out'].astype(float)

In [15]:
BR= Batsman.groupby(by=['Players','Team'])[['Match Played','Batsman Runs','Balls','Fours','Sixes','50s','100s','Times Out']].sum().nlargest(100,columns=['Batsman Runs'])

In [16]:
BR['Strike Rate'] = BR['Batsman Runs']/BR['Balls']*100

In [17]:
batsman= BR.round(2)

In [18]:
batsman.loc[batsman['Times Out'] ==0,'Average']  = batsman['Batsman Runs']/batsman['Match Played']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] == 1),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] >= 2),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])
batsman.loc[(batsman['Times Out'] == 2) & (batsman['Match Played'] == 2),'Average'] = batsman['Batsman Runs']

In [19]:
batsman.loc[batsman['Balls'] >=1 , 'Innings'] = batsman['Match Played']

In [20]:
batsman.head(1)

,,Match Played,Batsman Runs,Balls,Fours,Sixes,50s,100s,Times Out,Strike Rate,Average,Innings
Players,Team,,,,,,,,,,,
Nitish Rana,Kolkata Knight Riders,2,137,103,15,6,2,0,0.0,133.01,68.5,2

In [21]:
batsman[batsman['Times Out'] ==1]

,,Match Played,Batsman Runs,Balls,Fours,Sixes,50s,100s,Times Out,Strike Rate,Average,Innings
Players,Team,,,,,,,,,,,
Manish Pandey,Sunrisers Hyderabad,3,101,90,4,5,1,0,1.0,112.22,50.5,3
Rishabh Pant,Delhi Capitals,2,66,44,11,0,1,0,1.0,150.00,66.0,2
Shahrukh Khan,Punjab Kings,2,53,40,5,2,0,0,1.0,132.50,53.0,2
Kieron Pollard,Mumbai Indians,3,47,39,3,3,0,0,1.0,120.51,23.5,3
Sam Curran,Chennai Super Kings,2,39,19,5,2,0,0,1.0,205.26,39.0,2
du Plessis,Chennai Super Kings,2,36,36,3,1,0,0,1.0,100.00,36.0,2
Abdul Samad,Sunrisers Hyderabad,3,26,18,1,2,0,0,1.0,144.44,13.0,3
Krunal Pandya,Mumbai Indians,3,25,19,4,0,0,0,1.0,131.58,12.5,3
Chris Woakes,Delhi Capitals,1,15,11,2,0,0,0,1.0,136.36,15.0,1
Jaydev Unadkat,Rajasthan Royals,1,11,7,0,1,0,0,1.0,157.14,11.0,1
Kagiso Rabada,Delhi Capitals,1,9,4,1,0,0,0,1.0,225.00,9.0,1
Mohammed Shami,Punjab Kings,1,9,12,0,0,0,0,1.0,75.00,9.0,1
Harshal Patel,Royal Challengers Banglore,1,4,3,0,0,0,0,1.0,133.33,4.0,1
Bhuvneshwar Kumar,Sunrisers Hyderabad,2,3,4,0,0,0,0,1.0,75.00,3.0,2
Harbhajan Singh,Kolkata Knight Riders,1,2,2,0,0,0,0,1.0,100.00,2.0,1
Jasprit Bumrah,Mumbai Indians,2,1,3,0,0,0,0,1.0,33.33,1.0,2
Mujeeb Ur Rahman,Sunrisers Hyderabad,1,1,1,0,0,0,0,1.0,100.00,1.0,1
Mohammed Siraj,Royal Challengers Banglore,1,0,1,0,0,0,0,1.0,0.00,0.0,1

## Most Runs

In [22]:
batsman[['Match Played','Innings','Batsman Runs','Average']].nlargest(15,'Batsman Runs').round(2)

,,Match Played,Innings,Batsman Runs,Average
Players,Team,,,,
Nitish Rana,Kolkata Knight Riders,2,2,137,68.50
Sanju Samson,Rajasthan Royals,2,2,123,61.50
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,36.67
Manish Pandey,Sunrisers Hyderabad,3,3,101,50.50
Glenn Maxwell,Royal Challengers Banglore,2,2,98,49.00
Suryakumar Yadav,Mumbai Indians,3,3,97,32.33
KL Rahul,Punjab Kings,2,2,96,48.00
Rohit Sharma,Mumbai Indians,3,3,94,31.33
Shikhar Dhawan,Delhi Capitals,2,2,94,47.00
David Warner,Sunrisers Hyderabad,3,3,93,31.00
Moeen Ali,Chennai Super Kings,2,2,82,41.00
Deepak Hooda,Punjab Kings,2,2,74,37.00
Prithvi Shaw,Delhi Capitals,2,2,74,37.00
Virat Kohli,Royal Challengers Banglore,2,2,66,33.00
Rishabh Pant,Delhi Capitals,2,2,66,66.00

## Highest Scores

In [23]:
Batsman[['Batsman Runs','Balls','Strike Rate','Vs']].nlargest(15,'Batsman Runs')

                  Batsman Runs  Balls  Strike Rate    Vs
Players
Sanju Samson               119     63       188.89  PBKS
KL Rahul                    91     50       182.00    RR
Shikhar Dhawan              85     54       157.41   CSK
Nitish Rana                 80     56       142.86   SRH
Prithvi Shaw                72     38       189.47   CSK
Deepak Hooda                64     28       228.57    RR
David Miller                62     43       144.19    DC
Manish Pandey               61     44       138.64   KKR
Glenn Maxwell               59     41       143.90   SRH
Nitish Rana                 57     47       121.28    MI
Suryakumar Yadav            56     36       155.56   KKR
Jonny Bairstow              55     40       137.50   KKR
Suresh Raina                54     36       150.00    DC
David Warner                54     37       145.95   RCB
Rahul Tripathi              53     29       182.76   SRH

## Best Batting Strike Rate

In [24]:
SR= batsman[batsman['Batsman Runs'] >=50].nlargest(15,'Strike Rate')

In [25]:
SR[['Match Played','Innings','Batsman Runs','Strike Rate']].nlargest(15,'Strike Rate')

,,Match Played,Innings,Batsman Runs,Strike Rate
Players,Team,,,,
Sanju Samson,Rajasthan Royals,2,2,123,186.36
Deepak Hooda,Punjab Kings,2,2,74,172.09
Prithvi Shaw,Delhi Capitals,2,2,74,172.09
Rahul Tripathi,Kolkata Knight Riders,2,2,58,170.59
KL Rahul,Punjab Kings,2,2,96,168.42
Rishabh Pant,Delhi Capitals,2,2,66,150.00
Suryakumar Yadav,Mumbai Indians,3,3,97,149.23
Moeen Ali,Chennai Super Kings,2,2,82,149.09
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,146.67
Shikhar Dhawan,Delhi Capitals,2,2,94,144.62
David Miller,Rajasthan Royals,1,1,62,144.19
Glenn Maxwell,Royal Challengers Banglore,2,2,98,142.03
Suresh Raina,Chennai Super Kings,2,2,62,137.78
Nitish Rana,Kolkata Knight Riders,2,2,137,133.01
Shahrukh Khan,Punjab Kings,2,2,53,132.50

## Best Batting Average

In [26]:
batsman[['Match Played','Innings','Batsman Runs','Average']].nlargest(15,'Average')

,,Match Played,Innings,Batsman Runs,Average
Players,Team,,,,
Nitish Rana,Kolkata Knight Riders,2,2,137,68.5
Rishabh Pant,Delhi Capitals,2,2,66,66.0
David Miller,Rajasthan Royals,1,1,62,62.0
Sanju Samson,Rajasthan Royals,2,2,123,61.5
Shahrukh Khan,Punjab Kings,2,2,53,53.0
Manish Pandey,Sunrisers Hyderabad,3,3,101,50.5
Glenn Maxwell,Royal Challengers Banglore,2,2,98,49.0
Chris Lynn,Mumbai Indians,1,1,49,49.0
KL Rahul,Punjab Kings,2,2,96,48.0
Shikhar Dhawan,Delhi Capitals,2,2,94,47.0
Moeen Ali,Chennai Super Kings,2,2,82,41.0
Sam Curran,Chennai Super Kings,2,2,39,39.0
Chris Morris,Rajasthan Royals,2,2,38,38.0
Deepak Hooda,Punjab Kings,2,2,74,37.0
Prithvi Shaw,Delhi Capitals,2,2,74,37.0

## Most Fours

In [27]:
batsman[['Match Played','Innings','Batsman Runs','Fours']].nlargest(10,'Fours')

,,Match Played,Innings,Batsman Runs,Fours
Players,Team,,,,
Nitish Rana,Kolkata Knight Riders,2,2,137,15
Sanju Samson,Rajasthan Royals,2,2,123,13
Suryakumar Yadav,Mumbai Indians,3,3,97,12
Shikhar Dhawan,Delhi Capitals,2,2,94,11
Moeen Ali,Chennai Super Kings,2,2,82,11
Rishabh Pant,Delhi Capitals,2,2,66,11
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,9
David Warner,Sunrisers Hyderabad,3,3,93,9
Prithvi Shaw,Delhi Capitals,2,2,74,9
Glenn Maxwell,Royal Challengers Banglore,2,2,98,8

## Most Sixes

In [28]:
batsman[['Match Played','Innings','Batsman Runs','Sixes']].nlargest(10,'Sixes')

,,Match Played,Innings,Batsman Runs,Sixes
Players,Team,,,,
Sanju Samson,Rajasthan Royals,2,2,123,7
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,7
Nitish Rana,Kolkata Knight Riders,2,2,137,6
Deepak Hooda,Punjab Kings,2,2,74,6
Manish Pandey,Sunrisers Hyderabad,3,3,101,5
Glenn Maxwell,Royal Challengers Banglore,2,2,98,5
KL Rahul,Punjab Kings,2,2,96,5
Suryakumar Yadav,Mumbai Indians,3,3,97,4
Rohit Sharma,Mumbai Indians,3,3,94,4
Suresh Raina,Chennai Super Kings,2,2,62,4

# BOWLERS

In [29]:
bowler_played= df[['Team','Match Played','Over','Bowler Balls','Maiden','Bowler Runs','Wickets','Economy Rate','Vs']]

In [30]:
Bowler= bowler_played[bowler_played['Bowler Balls'] >=1]

In [31]:
W= Bowler.groupby(by=['Players','Team'])[['Match Played','Over','Bowler Balls','Maiden','Bowler Runs','Wickets']].sum().nlargest(100,'Wickets')

In [32]:
W['Economy'] = W['Bowler Runs']/W['Over']

In [33]:
W['Average'] = W['Bowler Runs']/W['Wickets']

In [34]:
W['Strike Rate'] = W['Bowler Balls']/W['Wickets']

In [35]:
bowler = W.round(2)

In [36]:
bowler.sort_values(by='Wickets',ascending=False).shape

(59, 9)

## Most Wickets

In [37]:
bowler[['Match Played','Over','Wickets','Average']].nlargest(10,'Wickets')

,,Match Played,Over,Wickets,Average
Players,Team,,,,
Rahul Chahar,Mumbai Indians,3,12.0,7,12.71
Harshal Patel,Royal Challengers Banglore,2,8.0,7,7.43
Andre Russell,Kolkata Knight Riders,2,5.0,6,7.83
Trent Boult,Mumbai Indians,3,11.4,6,15.17
Avesh Khan,Delhi Capitals,2,8.0,5,11.00
Mohammed Shami,Punjab Kings,2,8.0,4,13.50
Rashid Khan,Sunrisers Hyderabad,3,12.0,4,16.00
Arshdeep Singh,Punjab Kings,2,6.0,4,10.50
Chris Woakes,Delhi Capitals,2,7.0,4,10.00
Deepak Chahar,Chennai Super Kings,2,8.0,4,12.25

## Best Bowling Average

In [38]:
bowler[['Match Played','Over','Bowler Runs','Wickets','Average']].nsmallest(10,'Average')

,,Match Played,Over,Bowler Runs,Wickets,Average
Players,Team,,,,,
Jaydev Unadkat,Rajasthan Royals,1,4.0,15,3,5.00
Shahbaz Ahmed,Royal Challengers Banglore,2,3.0,21,3,7.00
Harshal Patel,Royal Challengers Banglore,2,8.0,52,7,7.43
Andre Russell,Kolkata Knight Riders,2,5.0,47,6,7.83
Chris Woakes,Delhi Capitals,2,7.0,40,4,10.00
Jason Holder,Sunrisers Hyderabad,1,4.0,30,3,10.00
Arshdeep Singh,Punjab Kings,2,6.0,42,4,10.50
Avesh Khan,Delhi Capitals,2,8.0,55,5,11.00
Deepak Chahar,Chennai Super Kings,2,8.0,49,4,12.25
Rahul Chahar,Mumbai Indians,3,12.0,89,7,12.71

## Best Economy

In [39]:
bowler[['Match Played','Over','Wickets','Economy']].nsmallest(10,'Economy')

,,Match Played,Over,Wickets,Economy
Players,Team,,,,
Jaydev Unadkat,Rajasthan Royals,1,4.0,3,3.75
Abhishek Sharma,Sunrisers Hyderabad,1,1.0,0,5.00
Rashid Khan,Sunrisers Hyderabad,3,12.0,4,5.33
Jasprit Bumrah,Mumbai Indians,3,12.0,3,5.67
Chris Woakes,Delhi Capitals,2,7.0,4,5.71
Ravindra Jadeja,Chennai Super Kings,2,6.0,0,5.83
Mohammed Siraj,Royal Challengers Banglore,2,8.0,2,5.88
Khaleel Ahmed,Sunrisers Hyderabad,1,4.0,1,6.00
Deepak Chahar,Chennai Super Kings,2,8.0,4,6.12
Krunal Pandya,Mumbai Indians,3,11.0,3,6.18

## Best Strike Rate

In [40]:
SR= bowler[bowler['Wickets'] >=5].nlargest(5,'Strike Rate')

In [41]:
SR[['Match Played','Over','Wickets','Strike Rate']].nsmallest(5,'Strike Rate')

,,Match Played,Over,Wickets,Strike Rate
Players,Team,,,,
Andre Russell,Kolkata Knight Riders,2,5.0,6,5.00
Harshal Patel,Royal Challengers Banglore,2,8.0,7,6.86
Avesh Khan,Delhi Capitals,2,8.0,5,9.60
Rahul Chahar,Mumbai Indians,3,12.0,7,10.29
Trent Boult,Mumbai Indians,3,11.4,6,11.67

# FIELDER

In [42]:
fielder_played = df[['Team','Match Played','Catches','Run Out']]

In [43]:
Fielder = fielder_played[(fielder_played['Catches'] >=1) |(fielder_played['Run Out'] >=1)]

In [44]:
Catches = Fielder.groupby(by=['Players','Team'])[['Match Played','Catches']].sum().nlargest(10,'Catches')

In [45]:
Catches

                                             Match Played  Catches
Players          Team
Shikhar Dhawan   Delhi Capitals                         2        6
Daniel Christian Royal Challengers Banglore             2        3
Deepak Hooda     Punjab Kings                           2        3
KL Rahul         Punjab Kings                           2        3
Manish Pandey    Sunrisers Hyderabad                    2        3
Suryakumar Yadav Mumbai Indians                         2        3
Vijay Shankar    Sunrisers Hyderabad                    3        3
Wriddhiman Saha  Sunrisers Hyderabad                    2        3
AB de Villiers   Royal Challengers Banglore             2        2
Abdul Samad      Sunrisers Hyderabad                    1        2

In [46]:
Run_Out = Fielder.groupby(by=['Players','Team'])[['Match Played','Run Out']].sum().nlargest(10,'Run Out')

In [47]:
Run_Out

                                            Match Played  Run Out
Players         Team
Hardik Pandya   Mumbai Indians                         1        2
Krunal Pandya   Mumbai Indians                         2        2
Virat Kohli     Royal Challengers Banglore             2        2
Chris Woakes    Delhi Capitals                         1        1
David Miller    Rajasthan Royals                       1        1
Jasprit Bumrah  Mumbai Indians                         1        1
Mohammed Siraj  Royal Challengers Banglore             1        1
Quinton de Kock Mumbai Indians                         1        1
Ravindra Jadeja Chennai Super Kings                    1        1
Riyan Parag     Rajasthan Royals                       2        1