In [1]:
import pandas as pd
import os
pd.options.mode.chained_assignment= None

In [2]:
files= [file for file in os.listdir('./CSV Files')]

all_matches_data=pd.DataFrame()

for file in files:
    df=pd.read_csv('./CSV Files/'+file)
    all_matches_data=pd.concat([all_matches_data,df])

In [3]:
# all_matches_data.to_csv('Combo_Match1_to_Match11.csv',index=False)

In [4]:
 df= pd.read_csv('Combo CSV Files\Combo_Match1_to_Match11.csv',index_col='Players')

In [5]:
df.Fours.sum()

334

In [6]:
df.Sixes.sum()

138

In [7]:
df.groupby('Team').Fours.sum().nlargest(8)

Team
Delhi Capitals                65
Royal Challengers Banglore    48
Kolkata Knight Riders         46
Punjab Kings                  45
Mumbai Indians                41
Rajasthan Royals              34
Chennai Super Kings           28
Sunrisers Hyderabad           27
Name: Fours, dtype: int64

In [8]:
df.groupby('Team').Sixes.sum().nlargest(8)

Team
Punjab Kings                  25
Sunrisers Hyderabad           22
Kolkata Knight Riders         20
Rajasthan Royals              18
Mumbai Indians                15
Royal Challengers Banglore    15
Chennai Super Kings           12
Delhi Capitals                11
Name: Sixes, dtype: int64

In [9]:
batsman_played= df[['Team','Match Played','Batsman Runs','Balls','Fours','Sixes','Strike Rate','50s','100s','Vs','Times Out']]

In [10]:
Batsman= batsman_played[batsman_played['Balls'] >=1]

In [11]:
Batsman.replace(to_replace=['Yes','No'],value=[0,1],inplace=True)

In [12]:
Batsman['Times Out'] = Batsman['Times Out'].astype(float)

In [13]:
BR= Batsman.groupby(by=['Players','Team'])[['Match Played','Batsman Runs','Balls','Fours','Sixes','50s','100s','Times Out']].sum().nlargest(100,columns=['Batsman Runs'])

In [14]:
BR['Strike Rate'] = BR['Batsman Runs']/BR['Balls']*100

In [15]:
batsman= BR.round(2)

In [16]:
batsman.loc[batsman['Times Out'] ==0,'Average']  = batsman['Batsman Runs']/batsman['Match Played']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] == 1),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] >= 2),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])
batsman.loc[(batsman['Times Out'] == 2) & (batsman['Match Played'] == 2),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 3) & (batsman['Match Played'] == 3),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 2) & (batsman['Match Played'] >= 3),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])

In [17]:
batsman.loc[batsman['Balls'] >=1 , 'Innings'] = batsman['Match Played']

In [18]:
batsman.head(1)

,,Match Played,Batsman Runs,Balls,Fours,Sixes,50s,100s,Times Out,Strike Rate,Average,Innings
Players,Team,,,,,,,,,,,
Shikhar Dhawan,Delhi Capitals,3,186,114,24,4,2,0,0.0,163.16,62.0,3

## Most Runs

In [19]:
batsman[['Match Played','Innings','Batsman Runs','Average']].nlargest(20,'Batsman Runs').round(2)

,,Match Played,Innings,Batsman Runs,Average
Players,Team,,,,
Shikhar Dhawan,Delhi Capitals,3,3,186,62.00
Glenn Maxwell,Royal Challengers Banglore,3,3,176,58.67
KL Rahul,Punjab Kings,3,3,157,52.33
Nitish Rana,Kolkata Knight Riders,3,3,155,51.67
AB de Villiers,Royal Challengers Banglore,3,3,125,62.50
Sanju Samson,Rajasthan Royals,2,2,123,61.50
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,36.67
Prithvi Shaw,Delhi Capitals,3,3,106,35.33
Manish Pandey,Sunrisers Hyderabad,3,3,101,50.50
Suryakumar Yadav,Mumbai Indians,3,3,97,32.33
Deepak Hooda,Punjab Kings,3,3,96,48.00
Rohit Sharma,Mumbai Indians,3,3,94,31.33
David Warner,Sunrisers Hyderabad,3,3,93,31.00
Rahul Tripathi,Kolkata Knight Riders,3,3,83,27.67
Mayank Agarwal,Punjab Kings,3,3,83,27.67
Moeen Ali,Chennai Super Kings,2,2,82,41.00
Rishabh Pant,Delhi Capitals,3,3,81,40.50
Virat Kohli,Royal Challengers Banglore,3,3,71,23.67
Shubman Gill,Kolkata Knight Riders,3,3,69,23.00
Shahrukh Khan,Punjab Kings,3,3,68,68.00

## Highest Scores

In [20]:
Batsman[['Batsman Runs','Balls','Strike Rate','Vs']].nlargest(15,'Batsman Runs')

                Batsman Runs  Balls  Strike Rate    Vs
Players
Sanju Samson             119     63       188.89  PBKS
Shikhar Dhawan            92     49       187.76  PBKS
KL Rahul                  91     50       182.00    RR
Shikhar Dhawan            85     54       157.41   CSK
Nitish Rana               80     56       142.86   SRH
Glenn Maxwell             78     49       159.18   KKR
AB de Villiers            76     34       223.53   KKR
Prithvi Shaw              72     38       189.47   CSK
Mayank Agarwal            69     36       191.67    DC
Deepak Hooda              64     28       228.57    RR
David Miller              62     43       144.19    DC
KL Rahul                  61     51       119.61    DC
Manish Pandey             61     44       138.64   KKR
Glenn Maxwell             59     41       143.90   SRH
Nitish Rana               57     47       121.28    MI

## Best Strike Rate

In [21]:
SR= batsman[batsman['Batsman Runs'] >=50].nlargest(15,'Strike Rate')

In [22]:
SR[['Match Played','Innings','Batsman Runs','Strike Rate']].nlargest(15,'Strike Rate')

,,Match Played,Innings,Batsman Runs,Strike Rate
Players,Team,,,,
AB de Villiers,Royal Challengers Banglore,3,3,125,189.39
Sanju Samson,Rajasthan Royals,2,2,123,186.36
Prithvi Shaw,Delhi Capitals,3,3,106,176.67
Mayank Agarwal,Punjab Kings,3,3,83,176.60
Deepak Hooda,Punjab Kings,3,3,96,171.43
Shikhar Dhawan,Delhi Capitals,3,3,186,163.16
Rahul Tripathi,Kolkata Knight Riders,3,3,83,153.70
Shahrukh Khan,Punjab Kings,3,3,68,151.11
Shubman Gill,Kolkata Knight Riders,3,3,69,150.00
Suryakumar Yadav,Mumbai Indians,3,3,97,149.23
Glenn Maxwell,Royal Challengers Banglore,3,3,176,149.15
Moeen Ali,Chennai Super Kings,2,2,82,149.09
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,146.67
KL Rahul,Punjab Kings,3,3,157,145.37
David Miller,Rajasthan Royals,1,1,62,144.19

## Best Batting Average

In [23]:
batsman[['Match Played','Innings','Batsman Runs','Average']].nlargest(15,'Average').round(2)

,,Match Played,Innings,Batsman Runs,Average
Players,Team,,,,
Shahrukh Khan,Punjab Kings,3,3,68,68.00
AB de Villiers,Royal Challengers Banglore,3,3,125,62.50
Shikhar Dhawan,Delhi Capitals,3,3,186,62.00
David Miller,Rajasthan Royals,1,1,62,62.00
Sanju Samson,Rajasthan Royals,2,2,123,61.50
Glenn Maxwell,Royal Challengers Banglore,3,3,176,58.67
KL Rahul,Punjab Kings,3,3,157,52.33
Nitish Rana,Kolkata Knight Riders,3,3,155,51.67
Manish Pandey,Sunrisers Hyderabad,3,3,101,50.50
Chris Lynn,Mumbai Indians,1,1,49,49.00
Deepak Hooda,Punjab Kings,3,3,96,48.00
Moeen Ali,Chennai Super Kings,2,2,82,41.00
Rishabh Pant,Delhi Capitals,3,3,81,40.50
Sam Curran,Chennai Super Kings,2,2,39,39.00
Chris Morris,Rajasthan Royals,2,2,38,38.00