In [1]:
import pandas as pd
import os
pd.options.mode.chained_assignment= None

In [2]:
files= [file for file in os.listdir('./CSV Files')]

all_matches_data=pd.DataFrame()

for file in files:
    df=pd.read_csv('./CSV Files/'+file)
    all_matches_data=pd.concat([all_matches_data,df])

In [3]:
# all_matches_data.to_csv('Combo_Match1_to_Match10.csv',index=False)

In [5]:
 df= pd.read_csv('Combo CSV Files\Combo_Match1_to_Match10.csv',index_col='Players')

In [6]:
df.Sixes.sum()

122

In [7]:
df.Fours.sum()

296

In [8]:
df.groupby('Team').Fours.sum().nlargest(8)

Team
Royal Challengers Banglore    48
Kolkata Knight Riders         46
Delhi Capitals                44
Mumbai Indians                41
Rajasthan Royals              34
Chennai Super Kings           28
Punjab Kings                  28
Sunrisers Hyderabad           27
Name: Fours, dtype: int64

In [9]:
df.groupby('Team').Sixes.sum().nlargest(8)

Team
Sunrisers Hyderabad           22
Kolkata Knight Riders         20
Rajasthan Royals              18
Mumbai Indians                15
Punjab Kings                  15
Royal Challengers Banglore    15
Chennai Super Kings           12
Delhi Capitals                 5
Name: Sixes, dtype: int64

# BATSMAN

In [10]:
batsman_played= df[['Team','Match Played','Batsman Runs','Balls','Fours','Sixes','Strike Rate','50s','100s','Vs','Times Out']]

In [11]:
Batsman= batsman_played[batsman_played['Balls'] >=1]

In [12]:
Batsman.replace(to_replace=['Yes','No'],value=[0,1],inplace=True)

In [13]:
Batsman['Times Out'] = Batsman['Times Out'].astype(float)

In [14]:
BR= Batsman.groupby(by=['Players','Team'])[['Match Played','Batsman Runs','Balls','Fours','Sixes','50s','100s','Times Out']].sum().nlargest(100,columns=['Batsman Runs'])

In [15]:
BR['Strike Rate'] = BR['Batsman Runs']/BR['Balls']*100

In [16]:
batsman= BR.round(2)

In [17]:
batsman.loc[batsman['Times Out'] ==0,'Average']  = batsman['Batsman Runs']/batsman['Match Played']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] == 1),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] >= 2),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])
batsman.loc[(batsman['Times Out'] == 2) & (batsman['Match Played'] == 2),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 3) & (batsman['Match Played'] == 3),'Average'] = batsman['Batsman Runs']

In [18]:
batsman.loc[batsman['Balls'] >=1 , 'Innings'] = batsman['Match Played']

In [20]:
batsman.head(1).round(2)

,,Match Played,Batsman Runs,Balls,Fours,Sixes,50s,100s,Times Out,Strike Rate,Average,Innings
Players,Team,,,,,,,,,,,
Glenn Maxwell,Royal Challengers Banglore,3,176,118,17,8,2,0,0.0,149.15,58.67,3

## Most Runs

In [21]:
batsman[['Match Played','Innings','Batsman Runs','Average']].nlargest(15,'Batsman Runs').round(2)

,,Match Played,Innings,Batsman Runs,Average
Players,Team,,,,
Glenn Maxwell,Royal Challengers Banglore,3,3,176,58.67
Nitish Rana,Kolkata Knight Riders,3,3,155,51.67
AB de Villiers,Royal Challengers Banglore,3,3,125,62.50
Sanju Samson,Rajasthan Royals,2,2,123,61.50
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,36.67
Manish Pandey,Sunrisers Hyderabad,3,3,101,50.50
Suryakumar Yadav,Mumbai Indians,3,3,97,32.33
KL Rahul,Punjab Kings,2,2,96,48.00
Rohit Sharma,Mumbai Indians,3,3,94,31.33
Shikhar Dhawan,Delhi Capitals,2,2,94,47.00
David Warner,Sunrisers Hyderabad,3,3,93,31.00
Rahul Tripathi,Kolkata Knight Riders,3,3,83,27.67
Moeen Ali,Chennai Super Kings,2,2,82,41.00
Deepak Hooda,Punjab Kings,2,2,74,37.00
Prithvi Shaw,Delhi Capitals,2,2,74,37.00

## Highest Score

In [22]:
Batsman[['Batsman Runs','Balls','Strike Rate','Vs']].nlargest(15,'Batsman Runs')

                  Batsman Runs  Balls  Strike Rate    Vs
Players
Sanju Samson               119     63       188.89  PBKS
KL Rahul                    91     50       182.00    RR
Shikhar Dhawan              85     54       157.41   CSK
Nitish Rana                 80     56       142.86   SRH
Glenn Maxwell               78     49       159.18   KKR
AB de Villiers              76     34       223.53   KKR
Prithvi Shaw                72     38       189.47   CSK
Deepak Hooda                64     28       228.57    RR
David Miller                62     43       144.19    DC
Manish Pandey               61     44       138.64   KKR
Glenn Maxwell               59     41       143.90   SRH
Nitish Rana                 57     47       121.28    MI
Suryakumar Yadav            56     36       155.56   KKR
Jonny Bairstow              55     40       137.50   KKR
Suresh Raina                54     36       150.00    DC

## Best Batting Strike Rate

In [23]:
SR= batsman[batsman['Batsman Runs'] >=50].nlargest(15,'Strike Rate')

In [24]:
SR[['Match Played','Innings','Batsman Runs','Strike Rate']].nlargest(15,'Strike Rate')

,,Match Played,Innings,Batsman Runs,Strike Rate
Players,Team,,,,
AB de Villiers,Royal Challengers Banglore,3,3,125,189.39
Sanju Samson,Rajasthan Royals,2,2,123,186.36
Deepak Hooda,Punjab Kings,2,2,74,172.09
Prithvi Shaw,Delhi Capitals,2,2,74,172.09
KL Rahul,Punjab Kings,2,2,96,168.42
Rahul Tripathi,Kolkata Knight Riders,3,3,83,153.70
Shubman Gill,Kolkata Knight Riders,3,3,69,150.00
Rishabh Pant,Delhi Capitals,2,2,66,150.00
Suryakumar Yadav,Mumbai Indians,3,3,97,149.23
Glenn Maxwell,Royal Challengers Banglore,3,3,176,149.15
Moeen Ali,Chennai Super Kings,2,2,82,149.09
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,146.67
Shikhar Dhawan,Delhi Capitals,2,2,94,144.62
David Miller,Rajasthan Royals,1,1,62,144.19
Suresh Raina,Chennai Super Kings,2,2,62,137.78

## Most Fours

In [25]:
batsman[['Match Played','Innings','Batsman Runs','Fours']].nlargest(10,'Fours')

,,Match Played,Innings,Batsman Runs,Fours
Players,Team,,,,
Glenn Maxwell,Royal Challengers Banglore,3,3,176,17
Nitish Rana,Kolkata Knight Riders,3,3,155,17
AB de Villiers,Royal Challengers Banglore,3,3,125,13
Sanju Samson,Rajasthan Royals,2,2,123,13
Suryakumar Yadav,Mumbai Indians,3,3,97,12
Shikhar Dhawan,Delhi Capitals,2,2,94,11
Moeen Ali,Chennai Super Kings,2,2,82,11
Rishabh Pant,Delhi Capitals,2,2,66,11
Rahul Tripathi,Kolkata Knight Riders,3,3,83,10
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,9

## Most Sixes

In [26]:
batsman[['Match Played','Innings','Batsman Runs','Sixes']].nlargest(10,'Sixes')

,,Match Played,Innings,Batsman Runs,Sixes
Players,Team,,,,
Glenn Maxwell,Royal Challengers Banglore,3,3,176,8
Nitish Rana,Kolkata Knight Riders,3,3,155,7
Sanju Samson,Rajasthan Royals,2,2,123,7
Jonny Bairstow,Sunrisers Hyderabad,3,3,110,7
Deepak Hooda,Punjab Kings,2,2,74,6
AB de Villiers,Royal Challengers Banglore,3,3,125,5
Manish Pandey,Sunrisers Hyderabad,3,3,101,5
KL Rahul,Punjab Kings,2,2,96,5
Suryakumar Yadav,Mumbai Indians,3,3,97,4
Rohit Sharma,Mumbai Indians,3,3,94,4