In [1]:
import pandas as pd
import os
pd.options.mode.chained_assignment= None

In [2]:
files= [file for file in os.listdir('./CSV Files')]

all_matches_data=pd.DataFrame()

for file in files:
    df=pd.read_csv('./CSV Files/'+file)
    all_matches_data=pd.concat([all_matches_data,df])

In [3]:
# all_matches_data.to_csv('Combo_Match1_to_Match19.csv',index=False)

In [4]:
 df= pd.read_csv('Combo CSV Files\Combo_Match1_to_Match19.csv',index_col='Players')

In [5]:
df.Fours.sum()

530

In [6]:
df.Sixes.sum()

238

In [7]:
df.groupby('Team').Sixes.sum().nlargest(8)

Team
Chennai Super Kings           45
Kolkata Knight Riders         39
Punjab Kings                  33
Rajasthan Royals              32
Royal Challengers Banglore    28
Sunrisers Hyderabad           26
Mumbai Indians                23
Delhi Capitals                12
Name: Sixes, dtype: int64

In [8]:
df.groupby('Team').Fours.sum().nlargest(8)

Team
Delhi Capitals                79
Chennai Super Kings           76
Royal Challengers Banglore    75
Rajasthan Royals              73
Kolkata Knight Riders         71
Punjab Kings                  64
Mumbai Indians                59
Sunrisers Hyderabad           33
Name: Fours, dtype: int64

# 1. BATSMAN

In [9]:
Batsman=df[['Team','Match Played','Batsman Runs','Balls','Fours','Sixes','Strike Rate','50s','100s','Vs','Times Out']]

In [10]:
Batsman.replace(to_replace=['Yes','No'],value=[0,1],inplace=True)

In [11]:
Batsman['Times Out'] = Batsman['Times Out'].astype(float)

In [12]:
BR=Batsman.groupby(by=['Players','Team'])[['Match Played','Batsman Runs','Balls','Fours','Sixes','50s','100s','Vs','Times Out']].sum().nlargest(1000,'Batsman Runs')

In [13]:
BR['Strike Rate'] = BR['Batsman Runs']/BR['Balls']*100

In [14]:
batsman= BR.round(2)

In [15]:
batsman.loc[batsman['Balls'] >=1 , 'Innings'] = batsman['Match Played']

In [16]:
batsman.loc[(batsman['Times Out'] == 0) & (batsman['Match Played'] >=1) ,'Average'] = batsman['Batsman Runs']/batsman['Match Played']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] == 1),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 1) & (batsman['Match Played'] >= 2),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])
batsman.loc[(batsman['Times Out'] == 2) & (batsman['Match Played'] == 2),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 2) & (batsman['Match Played'] >= 3),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])
batsman.loc[(batsman['Times Out'] == 3) & (batsman['Match Played'] == 3),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 3) & (batsman['Match Played'] >=4),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])
batsman.loc[(batsman['Times Out'] == 4) & (batsman['Match Played'] ==4),'Average'] = batsman['Batsman Runs']
batsman.loc[(batsman['Times Out'] == 4) & (batsman['Match Played'] >=5),'Average'] = batsman['Batsman Runs']/(batsman['Match Played']-batsman['Times Out'])
batsman.loc[(batsman['Times Out'] == 5) & (batsman['Match Played'] ==5),'Average'] = batsman['Batsman Runs']

# 1. a) Most Runs

In [17]:
batsman[['Match Played','Batsman Runs','Average']].nlargest(15,'Batsman Runs').round(2)

,,Match Played,Batsman Runs,Average
Players,Team,,,
Shikhar Dhawan,Delhi Capitals,4,231,57.75
KL Rahul,Punjab Kings,5,221,55.25
du Plessis,Chennai Super Kings,5,214,71.33
Rohit Sharma,Mumbai Indians,5,201,40.20
Glenn Maxwell,Royal Challengers Banglore,5,198,49.50
Sanju Samson,Rajasthan Royals,5,187,46.75
Nitish Rana,Kolkata Knight Riders,5,186,37.20
Jonny Bairstow,Sunrisers Hyderabad,4,173,57.67
Devdutt Padikkal,Royal Challengers Banglore,4,171,57.00
Suryakumar Yadav,Mumbai Indians,5,154,30.80
Virat Kohli,Royal Challengers Banglore,5,151,37.75
Moeen Ali,Chennai Super Kings,4,133,33.25
David Warner,Sunrisers Hyderabad,4,130,32.50
Mayank Agarwal,Punjab Kings,5,130,26.00
AB de Villiers,Royal Challengers Banglore,5,129,43.00

# 2. b) Highest Scores

In [19]:
Batsman[['Batsman Runs','Balls','Strike Rate','Vs']].nlargest(15,'Batsman Runs')

                  Batsman Runs  Balls  Strike Rate    Vs
Players
Sanju Samson               119     63       188.89  PBKS
Devdutt Padikkal           101     52       194.23    RR
du Plessis                  95     60       158.33   KKR
Shikhar Dhawan              92     49       187.76  PBKS
KL Rahul                    91     50       182.00    RR
Shikhar Dhawan              85     54       157.41   CSK
Nitish Rana                 80     56       142.86   SRH
Glenn Maxwell               78     49       159.18   KKR
AB de Villiers              76     34       223.53   KKR
Virat Kohli                 72     47       153.19    RR
Prithvi Shaw                72     38       189.47   CSK
Mayank Agarwal              69     36       191.67    DC
Pat Cummins                 66     34       194.12   CSK
Rituraj Gaikwad             64     42       152.38   KKR
Deepak Hooda                64     28       228.57    RR

# 1. c) Best Batting Average

In [20]:
Avg= batsman[batsman['Match Played'] >=2]
Avg[['Match Played','Batsman Runs','Average']].nlargest(15,'Average').round(2)

,,Match Played,Batsman Runs,Average
Players,Team,,,
du Plessis,Chennai Super Kings,5,214,71.33
Shikhar Dhawan,Delhi Capitals,4,231,57.75
Jonny Bairstow,Sunrisers Hyderabad,4,173,57.67
Devdutt Padikkal,Royal Challengers Banglore,4,171,57.00
KL Rahul,Punjab Kings,5,221,55.25
Lalit Yadav,Delhi Capitals,3,54,54.00
Ravindra Jadeja,Chennai Super Kings,5,102,51.00
Manish Pandey,Sunrisers Hyderabad,3,101,50.50
Glenn Maxwell,Royal Challengers Banglore,5,198,49.50
Sanju Samson,Rajasthan Royals,5,187,46.75
Shahrukh Khan,Punjab Kings,5,90,45.00
AB de Villiers,Royal Challengers Banglore,5,129,43.00
Rohit Sharma,Mumbai Indians,5,201,40.20
Virat Kohli,Royal Challengers Banglore,5,151,37.75
Nitish Rana,Kolkata Knight Riders,5,186,37.20

# 1. d) Best Batting Strike Rate

In [21]:
SR= batsman[batsman['Batsman Runs'] >=50]
SR[['Match Played','Batsman Runs','Strike Rate']].nlargest(15,'Strike Rate')

,,Match Played,Batsman Runs,Strike Rate
Players,Team,,,
Sam Curran,Chennai Super Kings,5,52,208.00
Ravindra Jadeja,Chennai Super Kings,5,102,192.45
Pat Cummins,Kolkata Knight Riders,5,82,190.70
Prithvi Shaw,Delhi Capitals,4,113,173.85
AB de Villiers,Royal Challengers Banglore,5,129,172.00
Deepak Hooda,Punjab Kings,5,109,162.69
Devdutt Padikkal,Royal Challengers Banglore,4,171,158.33
Andre Russell,Kolkata Knight Riders,5,108,156.52
Ambati Rayudu,Chennai Super Kings,5,64,156.10
Moeen Ali,Chennai Super Kings,4,133,152.87
Glenn Maxwell,Royal Challengers Banglore,5,198,148.87
Shikhar Dhawan,Delhi Capitals,4,231,148.08
Shahrukh Khan,Punjab Kings,5,90,145.16
Suryakumar Yadav,Mumbai Indians,5,154,143.93
Sanju Samson,Rajasthan Royals,5,187,143.85

# 1. e) Most Hundreds

In [22]:
batsman[['Match Played','Batsman Runs','100s']].nlargest(2,'100s')

                                             Match Played  Batsman Runs  100s
Players          Team
Sanju Samson     Rajasthan Royals                       5           187     1
Devdutt Padikkal Royal Challengers Banglore             4           171     1

# 1. f) Most Fifties

In [23]:
batsman[['Match Played','Batsman Runs','50s']].nlargest(15,'50s')

                                             Match Played  Batsman Runs  50s
Players          Team
KL Rahul         Punjab Kings                           5           221    3
Shikhar Dhawan   Delhi Capitals                         4           231    2
du Plessis       Chennai Super Kings                    5           214    2
Glenn Maxwell    Royal Challengers Banglore             5           198    2
Nitish Rana      Kolkata Knight Riders                  5           186    2
Jonny Bairstow   Sunrisers Hyderabad                    4           173    2
Rohit Sharma     Mumbai Indians                         5           201    1
Suryakumar Yadav Mumbai Indians                         5           154    1
Virat Kohli      Royal Challengers Banglore             5           151    1
David Warner     Sunrisers Hyderabad                    4           130    1
Mayank Agarwal   Punjab Kings                           5           130    1
AB de Villiers   Royal Challengers Banglore             5           129    1
Rahul Tripathi   Kolkata Knight Riders                  5           127    1
Rituraj Gaikwad  Chennai Super Kings                    5           117    1
Prithvi Shaw     Delhi Capitals                         4           113    1

# 1. g) Most Fours

In [24]:
batsman[['Match Played','Batsman Runs','Fours']].nlargest(15,'Fours')

                                             Match Played  Batsman Runs  Fours
Players          Team
Shikhar Dhawan   Delhi Capitals                         4           231     29
du Plessis       Chennai Super Kings                    5           214     21
Glenn Maxwell    Royal Challengers Banglore             5           198     20
Nitish Rana      Kolkata Knight Riders                  5           186     20
Devdutt Padikkal Royal Challengers Banglore             4           171     19
Suryakumar Yadav Mumbai Indians                         5           154     19
KL Rahul         Punjab Kings                           5           221     18
Sanju Samson     Rajasthan Royals                       5           187     17
Virat Kohli      Royal Challengers Banglore             5           151     16
Mayank Agarwal   Punjab Kings                           5           130     15
Rohit Sharma     Mumbai Indians                         5           201     14
Moeen Ali        Chennai Super Kings                    4           133     14
AB de Villiers   Royal Challengers Banglore             5           129     13
Chris Gayle      Punjab Kings                           5           119     13
Prithvi Shaw     Delhi Capitals                         4           113     13

# 1. h) Most Sixes

In [25]:
batsman[['Match Played','Batsman Runs','Sixes']].nlargest(15,'Sixes')

                                             Match Played  Batsman Runs  Sixes
Players          Team
KL Rahul         Punjab Kings                           5           221     10
Jonny Bairstow   Sunrisers Hyderabad                    4           173     10
Rohit Sharma     Mumbai Indians                         5           201      9
Sanju Samson     Rajasthan Royals                       5           187      9
Andre Russell    Kolkata Knight Riders                  5           108      9
du Plessis       Chennai Super Kings                    5           214      8
Glenn Maxwell    Royal Challengers Banglore             5           198      8
Nitish Rana      Kolkata Knight Riders                  5           186      8
Devdutt Padikkal Royal Challengers Banglore             4           171      8
Deepak Hooda     Punjab Kings                           5           109      8
Suresh Raina     Chennai Super Kings                    5           104      8
Pat Cummins      Kolkata Knight Riders                  5            82      8
Moeen Ali        Chennai Super Kings                    4           133      7
Ravindra Jadeja  Chennai Super Kings                    5           102      6
Ambati Rayudu    Chennai Super Kings                    5            64      6

# 2. BOWLER

In [26]:
bowler_played= df[['Team','Match Played','Over','Bowler Balls','Maiden','Bowler Runs','Wickets','Economy Rate','Vs']]

In [27]:
Bowler= bowler_played[bowler_played['Bowler Balls'] >=1]

In [28]:
W= Bowler.groupby(by=['Players','Team'])[['Match Played','Over','Bowler Balls','Maiden','Bowler Runs','Wickets']].sum().nlargest(100,'Wickets')

In [29]:
W['Economy'] = W['Bowler Runs']/W['Over']

In [30]:
W['Average'] = W['Bowler Runs']/W['Wickets']

In [31]:
W['Strike Rate'] = W['Bowler Balls']/W['Wickets']

In [32]:
bowler = W.round(2)

In [33]:
bowler['Wickets'] =bowler['Wickets'].astype(int)

In [34]:
bowler.sort_values(by='Wickets',ascending=False).shape

(78, 9)

# 2. a) Most Wickets

In [35]:
bowler[['Match Played','Over','Wickets','Average']].nlargest(20,'Wickets')

,,Match Played,Over,Wickets,Average
Players,Team,,,,
Harshal Patel,Royal Challengers Banglore,5,20.0,15,11.13
Chris Morris,Rajasthan Royals,5,18.0,9,18.00
Rahul Chahar,Mumbai Indians,5,20.0,9,15.22
Avesh Khan,Delhi Capitals,4,14.0,8,12.88
Deepak Chahar,Chennai Super Kings,5,17.0,8,16.88
Andre Russell,Kolkata Knight Riders,4,9.0,7,16.00
Chetan Sakariya,Rajasthan Royals,5,20.0,7,23.71
Kyle Jamieson,Royal Challengers Banglore,5,17.0,6,26.17
Arshdeep Singh,Punjab Kings,5,15.4,6,20.50
Varun Chakravarthy,Kolkata Knight Riders,5,20.0,6,26.83
Trent Boult,Mumbai Indians,5,17.8,6,24.00
Mohammed Shami,Punjab Kings,5,18.0,6,24.00
Sam Curran,Chennai Super Kings,5,17.0,5,30.60
Ravindra Jadeja,Chennai Super Kings,5,18.0,5,21.80
Prasidh Krishna,Kolkata Knight Riders,5,20.0,5,35.40
Rashid Khan,Sunrisers Hyderabad,4,16.0,5,16.20
Chris Woakes,Delhi Capitals,3,11.0,5,16.40
Mohammed Siraj,Royal Challengers Banglore,5,19.0,5,24.60
Jaydev Unadkat,Rajasthan Royals,3,12.0,4,20.00
Mustafizur Rahman,Rajasthan Royals,5,19.3,4,41.75

# 2. b) Best Bowling Average

In [36]:
BA= bowler[bowler['Wickets'] >5]
BA[['Match Played','Over','Wickets','Average']].nsmallest(15,'Average')

,,Match Played,Over,Wickets,Average
Players,Team,,,,
Harshal Patel,Royal Challengers Banglore,5,20.0,15,11.13
Avesh Khan,Delhi Capitals,4,14.0,8,12.88
Rahul Chahar,Mumbai Indians,5,20.0,9,15.22
Andre Russell,Kolkata Knight Riders,4,9.0,7,16.00
Deepak Chahar,Chennai Super Kings,5,17.0,8,16.88
Chris Morris,Rajasthan Royals,5,18.0,9,18.00
Arshdeep Singh,Punjab Kings,5,15.4,6,20.50
Chetan Sakariya,Rajasthan Royals,5,20.0,7,23.71
Trent Boult,Mumbai Indians,5,17.8,6,24.00
Mohammed Shami,Punjab Kings,5,18.0,6,24.00
Kyle Jamieson,Royal Challengers Banglore,5,17.0,6,26.17
Varun Chakravarthy,Kolkata Knight Riders,5,20.0,6,26.83

# 2. c) Best Economy

In [37]:
BE= bowler[bowler['Wickets'] >=1]
BE[['Match Played','Over','Wickets','Economy']].nsmallest(15,'Economy')

,,Match Played,Over,Wickets,Economy
Players,Team,,,,
Imran Tahir,Chennai Super Kings,1,4.0,2,4.00
Shivam Mavi,Kolkata Knight Riders,1,4.0,1,4.75
Rashid Khan,Sunrisers Hyderabad,4,16.0,5,5.06
Ravi Bishoni,Punjab Kings,1,4.0,2,5.25
Lalit Yadav,Delhi Capitals,2,5.0,1,5.60
Khaleel Ahmed,Sunrisers Hyderabad,2,8.0,4,5.62
Jayant Yadav,Mumbai Indians,2,8.0,1,5.62
Abhishek Sharma,Sunrisers Hyderabad,2,5.0,2,5.80
Ravindra Jadeja,Chennai Super Kings,5,18.0,5,6.06
Deepak Hooda,Punjab Kings,3,9.0,1,6.11
Moeen Ali,Chennai Super Kings,3,9.0,4,6.33
Jasprit Bumrah,Mumbai Indians,5,19.0,4,6.37
Mohammed Siraj,Royal Challengers Banglore,5,19.0,5,6.47
Jaydev Unadkat,Rajasthan Royals,3,12.0,4,6.67
Sunil Narine,Kolkata Knight Riders,2,8.0,1,6.75

# 2. d) Best Bowlinf Strike Rate

In [38]:
SR= bowler[bowler['Wickets'] >5]
SR[['Match Played','Over','Wickets','Strike Rate']].nsmallest(15,'Strike Rate')

,,Match Played,Over,Wickets,Strike Rate
Players,Team,,,,
Andre Russell,Kolkata Knight Riders,4,9.0,7,7.71
Harshal Patel,Royal Challengers Banglore,5,20.0,15,8.00
Avesh Khan,Delhi Capitals,4,14.0,8,10.50
Chris Morris,Rajasthan Royals,5,18.0,9,12.00
Deepak Chahar,Chennai Super Kings,5,17.0,8,12.75
Rahul Chahar,Mumbai Indians,5,20.0,9,13.33
Arshdeep Singh,Punjab Kings,5,15.4,6,15.67
Kyle Jamieson,Royal Challengers Banglore,5,17.0,6,17.00
Chetan Sakariya,Rajasthan Royals,5,20.0,7,17.14
Mohammed Shami,Punjab Kings,5,18.0,6,18.00
Trent Boult,Mumbai Indians,5,17.8,6,18.33
Varun Chakravarthy,Kolkata Knight Riders,5,20.0,6,20.00

# 3. FIELDER

In [39]:
fielder_played = df[['Team','Match Played','Catches','Run Out']]

# 3. a) Catches

In [40]:
 fielder_played.groupby(by=['Players','Team'])[['Match Played','Catches']].sum().nlargest(10,'Catches')

                                             Match Played  Catches
Players          Team
Ravindra Jadeja  Chennai Super Kings                    5        7
Shikhar Dhawan   Delhi Capitals                         4        7
Riyan Parag      Rajasthan Royals                       5        6
Daniel Christian Royal Challengers Banglore             3        5
Deepak Hooda     Punjab Kings                           5        5
AB de Villiers   Royal Challengers Banglore             5        4
Dhoni            Chennai Super Kings                    5        4
KL Rahul         Punjab Kings                           5        4
Rishabh Pant     Delhi Capitals                         4        4
Sanju Samson     Rajasthan Royals                       5        4

# 3. b) Run Outs

In [41]:
fielder_played.groupby(by=['Players','Team'])[['Match Played','Run Out']].sum().nlargest(10,'Run Out')

                                            Match Played  Run Out
Players         Team
Hardik Pandya   Mumbai Indians                         5        2
Krunal Pandya   Mumbai Indians                         5        2
Ravindra Jadeja Chennai Super Kings                    5        2
Virat Kohli     Royal Challengers Banglore             5        2
Chris Morris    Rajasthan Royals                       5        1
Chris Woakes    Delhi Capitals                         3        1
David Miller    Rajasthan Royals                       4        1
David Warner    Sunrisers Hyderabad                    4        1
Dinesh Karthik  Kolkata Knight Riders                  5        1
Imran Tahir     Chennai Super Kings                    1        1

# 4. ALL-ROUNDERS

In [42]:
All_Rounder = df.groupby(by=['Players','Team'])[['Match Played','Batsman Runs','Balls','Fours','Sixes','Over','Bowler Balls','Bowler Runs','Maiden','Wickets','Catches','Run Out','50s','100s']].sum()

In [43]:
all_rounder= All_Rounder[(All_Rounder['Balls'] >1) & (All_Rounder['Wickets'] >=1)]

In [44]:
all_rounder.shape

(46, 14)

In [45]:
all_rounder['Economy Rate'] = all_rounder['Bowler Runs']/all_rounder['Over']

In [46]:
all_rounder['Strike Rate'] = all_rounder['Batsman Runs']/all_rounder['Balls']*100

In [47]:
all_rounders= all_rounder.round(2)

# 4. a) All-Rounders with highest Runs

In [48]:
all_rounders[['Match Played','Batsman Runs','Wickets']].nlargest(10,'Batsman Runs')

                                       Match Played  Batsman Runs  Wickets
Players         Team
Moeen Ali       Chennai Super Kings               4           133      4.0
Deepak Hooda    Punjab Kings                      5           109      1.0
Andre Russell   Kolkata Knight Riders             5           108      7.0
Ravindra Jadeja Chennai Super Kings               5           102      5.0
Rahul Tewatia   Rajasthan Royals                  5            86      1.0
Pat Cummins     Kolkata Knight Riders             5            82      4.0
Kieron Pollard  Mumbai Indians                    5            65      1.0
Riyan Parag     Rajasthan Royals                  5            55      1.0
Lalit Yadav     Delhi Capitals                    3            54      1.0
Sam Curran      Chennai Super Kings               5            52      5.0

# 4. b) All-Rounders with highest Wickets

In [49]:
all_rounders[['Match Played','Batsman Runs','Wickets']].nlargest(10,'Wickets')

,,Match Played,Batsman Runs,Wickets
Players,Team,,,
Harshal Patel,Royal Challengers Banglore,5,4,15.0
Chris Morris,Rajasthan Royals,5,48,9.0
Rahul Chahar,Mumbai Indians,5,14,9.0
Andre Russell,Kolkata Knight Riders,5,108,7.0
Arshdeep Singh,Punjab Kings,5,1,6.0
Kyle Jamieson,Royal Challengers Banglore,5,43,6.0
Mohammed Shami,Punjab Kings,5,12,6.0
Varun Chakravarthy,Kolkata Knight Riders,5,2,6.0
Chris Woakes,Delhi Capitals,3,15,5.0
Mohammed Siraj,Royal Challengers Banglore,5,12,5.0